mysql:
  image: mysql:latest
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: Przedlando1
  volumes:
    - ./database/mysql:/var/lib/mysql
  container_name: mysql_service
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 8080:80
  links:
    - mysql
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
  container_name: phpmyadmin_service
apache2:
  image: piotrowskidariusz/apache
  ports:
    - 80:80
    - 10000:10000
  links:
    - mysql
  volumes:
    - ./magento2:/var/www/html
  container_name: apache2_service